env:
  global:
  - GCP_PROJECT_ID=terraform-292215
  - tf_version=0.13.4
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: JmLhEaxor7QJ+a/1HyoQ6MvuafPwSWQTNzqtuboCFzsmSdlx/jz0aYspD+kwrvR2lI2VzDoBRqk52dPrRJH/s00pm/PH3e4ipskuliZqaMmRzcQ3mXk2Ezk35ihQrQlqTsC4CI5lPQTYZxwzK4DW6KGmnOArzBDbLSBTUDXy5vT0MZgqzn3f9RiI56tR2ofr7cSGN63FzhB/K3QZiOmDuW7Es8d9dRldOKfXjvFQ9ThIr3URisqv2XK6NxmjW+tRQUjS0oc0OSfJQiFH6tLY2liKp9D+yZLLWWtn+YBQWsn7myQ9bzCQ5W1duS9w/RhlV8WvfXNcjO09Q4TWLxABBSw4Uvc/nts+5YL4DAdPAzVNXWKGzMATNlqq7g1bol5QgnJawYIx6ApnH0kqHmG1ixIpz1+d8W0Cjh7Mr51qPqIFUg7vYTGxCOAc6QJiADumUCSxxvTSbs4u5F1w40G21jvKLu+Tk5gzQxensV/P6eibcNqDiz2RwjYzkoV7sB+aK3/pDAWLJyclOpYqeiMYY6pU86FAH7kl9ePrcGWhSOf0TZerCSBxrYA/IqHr/6M2Z28Bq0t9yF9Q4q6r8oA6KT3Wa1svRdMvQIX1QVNLgERYwIAamy6USrbx6WGSImg91pAFSxNlcxfb/UYm3R4CvyYUH2LFmYZGKoTybYo7XBc=
  - secure: TN1Y6DC53YzJEA1AARb/bntiXFT1Aijd3ScFUw25ZwBeavRytMXIIAK9WFEJqDyatTnXMmhp5q/ouZPRUD3K67x31FLjpE9rqM2X4DitfRv7aHAB9kqoAXQFxsTH+84W1trE6zWmUOHF8pSquqyQt4sccIMFfzxfY0SgMMX1t50qt5yaWGsB7U6RkYYofOvqVdYNZOWFK+9OenT6Mx2a5ip1/cHWY6RM1g3+go6hS29bZFSFem7gepdUx7SVk/Oz57107ngMfv8KJtov/8XF2MCKEa0bV6wsPtw46TGCvMvGTKUh2apg0MVnr6iP7fKtr3xo59Dq6gEyUzttXwdk1epX/f3QKRMoBC3COE+qpv4a3KQTiacaQQ19g+aywpEuEVG4BHKE/rob+xbZvstuPgWzpLs/zuBb+vR2YMgpJcemqUjPRxONFwa69+5IMtga1+uMvz77/yus2IZYYtpnhOmNfKArB985GciDOT1lQ9kbZiCzS6PBNbkHEgI5aLMbLuw/yjTaVDB1PZSXIy46IZ9kTy6M6NxlfwGKq+e7E+Dr/zhcqqZJMlVr/8Csveo/diQI+kZOG9jZ2+sb9gacA+AxsnL7LOvT52vXKwaB1qkrJtoNX8iXZhRFoT/LlA29mQVfycW993N4zA7NZLGfjn3KQYEyThRqLdnTHXPCQMI=
  - secure: mbrh8vb43Ax7iJ6csdwFguSRzGR5/CtpJl4LGePMEeMum+CpK4SrCn8A/85lL1cX1tC66od0Klve5ORC6n52guuEniQqDJt5KarAGwodc4X0qSUlJarvFgFwTS6GkXnrbCC05DDlofEPA+yz8QsQW1TkPmMgU7rDTL3wpbFOgyrsFTDPMigL5mBbR3j+DjmE4ZyfSOCbfIUTL4HD5qBmQe98wxy1CwmCggtA5VkTE8GZXVBTjNdzcME6c+TLwV7T8yjaO5kAdKXKWrzxzzkPLVE7Fao5GQMHmHUo/SSheU0Q1+trIrPQDgsK+MBuC/RAzw3ZAxa7wDTMw5i5rJDu8OoEWqB/EV5mx7zJFD/rumdpNZFr1Ssvx0rjKv0zmMe9G9Vpe7rMSWjnB+MW02hhrkVX+hHW34HDMkla3fdpwOwpVjIzUf4MWJB5G/EbAKbKZ4b5IJymGw1/BD1vgbRH/mn29pOPn2+GBAc6Z7BoYMSKWSCAigE8QInbkuHNrsJ6nUF35pXOl1wQNeUAmUovMPmrvlO1xUJcFBck3PdBsG25p7ydgpi/bdDdHjHzNI+/xf8Qw7SEI703+TKGBz3uYh9dyFrBQAGwrwbEzNhXl/2+Ze1DCUXxzmSDJwFYZwkpcxz51wRQ0hMc94ZouBool2KZ58o4EUucbV2WjCe0rME=
  - secure: KkLKl1WlfOqtA2/CM/x75JRYlzfah69AU4CDp7/RkXHmdA0jZ8Mery8GG5ltCGC4ddBKl0Qot8Px1Fj/6fOkMf299gcfWWHZ+gFJGTc5K7AabJoU2fipLoeFa+zM/G+RyWfixcW2rEANoKXNECzXhQvbv6OCUjtuKd/vRRysJ4dY2ccJxoflkSh44PnYHxkn2nBjDdE1+H065d05IFj0ZHeu2f0wtg9iJy9pfOMOGXDPvb/kSNKidMJHxIvvkP6Mt0o7O+coCEBUmamnxaxa6b+c8KGro25evkwrU8yNP1/Ueu5oFI8jMCfG00wue8NsEMviDb2kYbO6DZdPDZI/IfxFL5ekEDjHr6+JP8IVlUCw1oly3JHvKQTHk+CPzAFdfodOO2dHuJyX67TXD7UlDRVDc0mZ37WMFIr6FkdFO8lPgKLLGqALEFL/xJQuWG8XL2vKNQMWvmevX8mFU2ZNo3FWfiY8BPoMcwT8dO0OhUB7QIs5cJuPOLppOZ1NrVDnWDmp/F5H3vCJEiKE/p6ZDf1la8khmZftuXtmC7TetX2zPFrw/c07maW7PNbRZAyr+YnUHQRtaGOCTBqxf/xEbN+YY4HSjBcrP+oYsbw+OI7cKApu34REDN6aoSzwrTcXXvWV2GnVtT0ShMLVRwuUp9g7yaWqOkCgL8YKbGiU5Ns=
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv
  -in google-key.json.enc -out google-key.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=google-key.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./google-key.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  export TF_VAR_logz_token=$LOGZ_TOKEN
  export TF_VAR_logz_url=$LOGZ_URL
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
